name: Deploy DR2 Ingest Asset Reconciler Lambda
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - intg
          - staging
          - prod
        default: 'intg'
      to-deploy:
        description: 'Version to deploy'
        required: true

permissions:
  id-token: write
  contents: write
jobs:
  deploy:
    uses: nationalarchives/dr2-github-actions/.github/workflows/lambda_deploy.yml@main
    with:
      lambda-name: ${{ github.event.inputs.environment }}-dr2-ingest-asset-reconciler
      deployment-package:  dr2-ingest-asset-reconciler.jar
      environment: ${{ github.event.inputs.environment }}
      to-deploy: ${{ github.event.inputs.to-deploy }}
    secrets:
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
